### ISSUE TITLE
unable to run on local

### ISSUE THREAD

**Issue by michondr** [turhansel/turtify#2]
Hi!

I've tried to run the app on local. I suppose that the only config is the `.env.local`

```
NEXTAUTH_URL="http://localhost:3000"
SPOTIFY_CLIENT_ID=xxxxxxxxxxxxxx
SPOTIFY_CLIENT_SECRET=yyyyyyyyyyyyyy
JWT_SECRET=foooooooo
```

but I gen this error and cannot find where it fires. could you please point me in any direction?

```
Unhandled Runtime Error
Error: URLs is malformed. Please use only absolute URLs - https://nextjs.org/docs/messages/middleware-relative-urls
```

![image](https://user-images.githubusercontent.com/29277166/173428948-035e3172-c072-46be-b0c9-cb436a615b2b.png)

I've tried `console.log()` on many places, last thing that works is redirect to `/login`, but I cannot further log anything in `00-get-access-token.js` where the route sits

**Comment by turhansel** [comment]
Hi!

Did you add callbackuri to spotify dashboard?

![Screen Shot 2022-06-15 at 10 45 05 PM](https://user-images.githubusercontent.com/63788958/173912787-67228595-d9a6-4b59-99a3-6f89c31be7e8.png)

My configurations are below. Can you check that?

![Screen Shot 2022-06-15 at 10 47 05 PM](https://user-images.githubusercontent.com/63788958/173913469-ed5b8954-ae68-4b93-b9dc-c8971a047e7d.png)

**Comment by michondr** [comment]
![image](https://user-images.githubusercontent.com/29277166/174251731-9b4408a4-a95d-4298-9494-27938ed7bf1a.png)

![image](https://user-images.githubusercontent.com/29277166/174251808-f1008973-64f9-4907-bcce-6c3eabacf466.png)

added, still the same output. is there a way to debug this in JS? (I'm more of a php guy, so this is new-ish to me)

**Comment by turhansel** [comment]
It is probably version related. can you send me an e-mail?
e-mail: turhansel@gmail.com
